Repository webpack-contrib/webpack-defaults, pull requests merged in 2018-09, with the labels that each got.

#137 refactor(task/templates): remove `vscode` launcher
  src/tasks/templates.js
  templates/.vscode/launch.json
Labels: pr_action: Discuss, priority: 3 (required), semver: Patch, severity: 5 (confusing), status: Needs triage, type: Refactor

#135 docs(templates/README): fix header links
  templates/README.md
Labels: semver: Patch, status: Approved, type: Documentation

#138 refactor(tasks/codecov): remove custom config
  config.json
  src/tasks/codecov.js
Labels: pr_action: Discuss, priority: 3 (required), semver: Patch, severity: 5 (confusing), status: Needs triage, type: Refactor

#134 ci: refactor setup
  src/tasks/package.js
  templates/.circleci/config.yml
Labels: pr_action: Rework, priority: 4 (important), semver: Patch, severity: 4 (inconvenient), status: Pending, type: CI

#143 refactor(tasks/package): simplify `commitlint` config
  src/tasks/package.js
  templates/commitlint.config.js
Labels: semver: Patch, status: Approved, type: Refactor

#144 chore(tasks/package): update `babel` v6.0.0...7.0.0 (`devDependencies`)
  config.json
  src/tasks/babel.js
  src/tasks/package.js
Labels: semver: Patch, status: Approved, type: Chore
