Repository webpack-contrib/webpack-defaults, pull requests merged in 2018-03, with the labels that each got.

#88 refactor: Webpack Defaults 2.x merge
  .babelrc
  .eslintignore
  .eslintrc
  .eslintrc.js
  .github/CODEOWNERS
  .gitignore
  CHANGELOG.md
  README.md
  config.json
  lib/post_install.js
  package-lock.json
  package.json
  src/tasks/appveyor.js
  src/tasks/babel.js
  src/tasks/codecov.js
  src/tasks/editorconfig.js
  src/tasks/eslint.js
  src/tasks/git.js
  src/tasks/package.js
  src/tasks/readme.js
  src/tasks/templates.js
  src/tasks/travis.js
  templates/.circleci/config.yml
  templates/.eslintrc.js
  templates/.github/CODEOWNERS
  templates/.prettierrc
  templates/.travis.yml
  templates/.vscode/launch.json
  templates/CHANGELOG.md
  templates/README.template
  templates/appveyor.yml
  templates/commitlint.config.js
  templates/src/cjs.js
  templates/src/index.js
  templates/src/options.json
  templates/test/errors.test.js
  templates/test/fixtures/fixture.js
  templates/test/fixtures/foo.js
  templates/test/helpers/compiler.js
  templates/test/loader.test.js
  templates/test/options.test.js
Labels: pr_action: Review, priority: 2 (urgent), semver: Major, type: Refactor

#96 feat(dotfile): add .editorconfig to templates
  config.json
  src/tasks/editorconfig.js
  src/tasks/templates.js
  templates/.editorconfig
Labels: semver: Minor, status: Approved

#99 fix(commitlint): fix type-enum options
  templates/commitlint.config.js
Labels: priority: 4 (important), severity: 3 (broken), status: Approved, type: Bug
